#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
RUNNER=${HIGH_VOL_STACK_RUNNER:-"${ROOT_DIR}/scripts/run-high-vol-stack-containerized.sh"}
RUN_DIR=${HIGH_VOL_STACK_RUN_DIR:?HIGH_VOL_STACK_RUN_DIR is required}
mkdir -p "${RUN_DIR}"

run_name=$(basename "${RUN_DIR}" | tr -cd '[:alnum:]_.-')
unit="tpl-high-vol-profit-${run_name}"
if systemctl --user is-active --quiet "${unit}.service"; then
  echo "${unit}.service is already running."
  exit 3
fi

environment_names=(
  HIGH_VOL_STACK_SOURCE_DIR
  HIGH_VOL_STACK_RUN_DIR
  HIGH_VOL_STACK_PYTHON_IMAGE
  HIGH_VOL_STACK_NODE_IMAGE
  CHRONOS2_AI_WORKER_URL
  FINCAST_AI_WORKER_URL
  CHRONOS2_AI_WORKER_TOKEN_FILE
  FINCAST_AI_WORKER_TOKEN_FILE
  RUST_WORKER_BINARY
  HIGH_VOL_STACK_FROM
  HIGH_VOL_STACK_TO
  HIGH_VOL_STACK_CALIBRATION_DAYS
  HIGH_VOL_STACK_DIAGNOSTIC_FROM
  HIGH_VOL_STACK_HOLDOUT_FROM
  HIGH_VOL_STACK_SMOKE
  HIGH_VOL_STACK_RUST_CONCURRENCY
  HIGH_VOL_STACK_DASHBOARD_RUN_ROOT
  HIGH_VOL_STACK_DASHBOARD_RUN_ID
  HIGH_VOL_STACK_DASHBOARD_PYTHON
)
systemd_environment=()
launch_environment="${RUN_DIR}/pipeline-launch.env"
launch_environment_tmp="${launch_environment}.tmp.$$"
umask 077
{
  printf '# Generated by %s at %s\n' "${BASH_SOURCE[0]}" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'export HIGH_VOL_STACK_RUNNER=%q\n' "${RUNNER}"
  for name in "${environment_names[@]}"; do
    if [[ -v "${name}" ]]; then
      printf 'export %s=%q\n' "${name}" "${!name}"
    fi
  done
} >"${launch_environment_tmp}"
mv "${launch_environment_tmp}" "${launch_environment}"

for name in "${environment_names[@]}"; do
  if [[ -v "${name}" ]]; then
    systemd_environment+=(--setenv="${name}=${!name}")
  fi
done

systemd-run --user \
  --unit="${unit}" \
  --collect \
  --property=Restart=no \
  --property=TimeoutStopSec=30 \
  "${systemd_environment[@]}" \
  "${RUNNER}"

printf '%s\n' "${unit}.service" >"${RUN_DIR}/pipeline.unit"
printf '%s\n' "${RUN_DIR}/pipeline.log" >"${RUN_DIR}/pipeline.log-path"
echo "${unit}.service"
echo "${RUN_DIR}"
