#!/usr/bin/env bash
set -euo pipefail

RUN_DIR=${1:-${HIGH_VOL_STACK_RUN_DIR:-}}
if [[ -z "${RUN_DIR}" || ! -d "${RUN_DIR}" ]]; then
  echo "Usage: $0 <run-dir>" >&2
  exit 2
fi

unit=$(cat "${RUN_DIR}/pipeline.unit" 2>/dev/null || true)
if [[ -n "${unit}" ]]; then
  systemctl --user show "${unit}" \
    --property=ActiveState,SubState,MainPID,ExecMainStatus \
    --no-pager 2>/dev/null || true
fi
for marker in SOURCE_COMPLETE COMPLETE FAILED STOP; do
  [[ -e "${RUN_DIR}/${marker}" ]] && echo "${marker}=present"
done
for status_file in state.json backtest-progress.json; do
  if [[ -f "${RUN_DIR}/${status_file}" ]]; then
    echo "${status_file}:"
    jq '{
      status,
      phase,
      heartbeatAt,
      completedAt,
      completedOrigins,
      totalOrigins,
      currentSymbol,
      currentOriginAt,
      models
    }' "${RUN_DIR}/${status_file}"
  fi
done
if [[ -f "${RUN_DIR}/pipeline.log" ]]; then
  echo "recent log:"
  tail -20 "${RUN_DIR}/pipeline.log"
fi

launch_environment="${RUN_DIR}/pipeline-launch.env"
if [[ -f "${launch_environment}" ]]; then
  # Generated by the start script with shell-escaped values.
  # shellcheck disable=SC1090
  source "${launch_environment}"
fi
dashboard_root=${HIGH_VOL_STACK_DASHBOARD_RUN_ROOT:-}
dashboard_run_id=${HIGH_VOL_STACK_DASHBOARD_RUN_ID:-monitor-$(basename "${RUN_DIR}")}
dashboard_state="${dashboard_root}/${dashboard_run_id}/state.json"
if [[ -n "${dashboard_root}" && -f "${dashboard_state}" ]]; then
  echo "dashboard state:"
  jq '{
    runId,
    status,
    updatedAt,
    phase: .experiment.phase,
    currentSymbol: .experiment.currentSymbol,
    currentOrigin: .experiment.currentOrigin,
    completedOrigins: .experiment.completedOrigins,
    totalOrigins: .experiment.totalOrigins
  }' "${dashboard_state}"
fi
if [[ -f "${RUN_DIR}/dashboard-sync.log" ]]; then
  echo "dashboard sync log:"
  tail -10 "${RUN_DIR}/dashboard-sync.log"
fi
