import type { AppConfig } from "../server/env.js";

export const verificationConfigDefaults = {
  readOnlyApiToken: "integration-read-only-token",
  readOnlyApiTokenSource: "READ_ONLY_API_TOKEN",
  trustProxy: [],
  gracefulShutdownTimeoutMs: 30_000,
  compute: {
    executionMode: "inline",
    resultPollMs: 250,
    resultDeadlineMs: 300_000,
    rustSocketPath: "/tmp/toss-portfolio-lens-compute.sock",
    rustSocketPoolSize: 2,
    rustSocketTimeoutMs: 300_000,
  },
  mcp: {
    enabled: false,
    authMode: "oauth",
    allowedOrigins: [],
    maxRequestsPerMinute: 60,
    maxConcurrentRuns: 1,
    maxRunsPerSubject: 2,
    maxQueuedRuns: 4,
    runDeadlineMs: 120_000,
    maxAssets: 20,
    maxCandidateBudget: 2_000,
    maxDateRangeYears: 20,
    inlineResultMaxRows: 1_000,
    inlineResultMaxBytes: 204_800,
    auditRetentionDays: 90,
  },
  scalping: {
    enabled: false,
    minimumTopCount: 5,
    maximumTopCount: 50,
    ai: {
      url: "ws://127.0.0.1:8765/ws/scalping-ai/v1",
      authTokenFile: "/tmp/toss-portfolio-lens-ai-token",
      timeoutMs: 120_000,
      connectTimeoutMs: 10_000,
      reconnectBaseMs: 250,
      reconnectMaxMs: 10_000,
      maximumInFlight: 4,
      maximumBatchSize: 50,
      maximumRequestBytes: 64 * 1024 * 1024,
      maximumResponseBytes: 128 * 1024 * 1024,
    },
    simulation: {
      maximumDurationMinutes: 390,
      decisionIntervalSeconds: 20,
      maximumActiveSessions: 2,
      selectionMaximumAttempts: 3,
      selectionRetryDelayMs: 15_000,
    },
  },
} as const satisfies Partial<AppConfig>;
