import type { AppConfig } from "../server/env.js";

export const verificationConfigDefaults = {
  readOnlyApiToken: "integration-read-only-token",
  trustProxy: [],
  gracefulShutdownTimeoutMs: 30_000,
  compute: {
    executionMode: "rust_socket",
    resultPollMs: 250,
    resultDeadlineMs: 300_000,
    rustSocketPath: "/tmp/toss-portfolio-lens-compute.sock",
    rustSocketPoolSize: 2,
    rustSocketTimeoutMs: 300_000,
    rustComputeMaxQueued: 32,
    rustComputeQueueTimeoutMs: 30_000,
  },
  mcp: {
    enabled: false,
    authMode: "oauth",
    allowedOrigins: [],
    maxRequestsPerMinute: 60,
    maxConcurrentRuns: 1,
    maxRunsPerSubject: 2,
    maxQueuedRuns: 4,
    runDeadlineMs: 120_000,
    maxAssets: 20,
    maxCandidateBudget: 2_000,
    maxDateRangeYears: 20,
    inlineResultMaxRows: 1_000,
    inlineResultMaxBytes: 204_800,
    auditRetentionDays: 90,
  },
  scalping: {
    enabled: false,
    minimumTopCount: 5,
    maximumTopCount: 50,
    ai: {
      url: "ws://127.0.0.1:8765/ws/scalping-ai/v2",
      authTokenFile: "/tmp/toss-portfolio-lens-ai-token",
      timeoutMs: 120_000,
      connectTimeoutMs: 10_000,
      reconnectBaseMs: 250,
      reconnectMaxMs: 10_000,
      maximumInFlight: 4,
      maximumBatchSize: 50,
      maximumRequestBytes: 64 * 1024 * 1024,
      maximumResponseBytes: 128 * 1024 * 1024,
    },
    simulation: {
      maximumDurationMinutes: 390,
      maximumActiveSessions: 2,
      selectionMaximumAttempts: 3,
      selectionRetryDelayMs: 15_000,
    },
    recorder: { enabled: false },
  },
  cryptoAi: {
    fincast: {
      url: "ws://127.0.0.1:18766/ws/scalping-ai/v2",
      authTokenFile: "/tmp/toss-portfolio-lens-fincast-token",
      timeoutMs: 120_000,
      connectTimeoutMs: 10_000,
      reconnectBaseMs: 250,
      reconnectMaxMs: 10_000,
      maximumInFlight: 1,
      maximumRequestBytes: 64 * 1024 * 1024,
      maximumResponseBytes: 128 * 1024 * 1024,
    },
    chronos2: {
      url: "ws://127.0.0.1:18767/ws/scalping-ai/v2",
      authTokenFile: "/tmp/toss-portfolio-lens-chronos2-token",
      timeoutMs: 120_000,
      connectTimeoutMs: 10_000,
      reconnectBaseMs: 250,
      reconnectMaxMs: 10_000,
      maximumInFlight: 1,
      maximumRequestBytes: 64 * 1024 * 1024,
      maximumResponseBytes: 128 * 1024 * 1024,
      authTokenMustDifferFromFile: "/tmp/toss-portfolio-lens-fincast-token",
    },
    sequentialDeadlineMs: 240_000,
    circuitBreaker: {
      failureThreshold: 3,
      cooldownMs: 60_000,
    },
  },
  cryptoSimulation: {
    maximumActiveSessions: 1,
  },
} as const satisfies Partial<AppConfig>;
